### ISSUE TITLE
[BUG] Power on and off fail to work on VMs with `.spec.running` field defined

### ISSUE THREAD

**Issue by starbops** [starbops/kubevirtbmc#19]
**Describe the bug**

Given the following VirtualMachine object defined:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

Users will fail to power on the VM with `ipmitool power on` command. There's no relevant logs shown in the corresponding `virtbmc` Pod.

If the VM is already in the running state, it cannot be powered off via `ipmitool power off` either. Same "unsupported command" output returned by the tool.

**To Reproduce**
1. Prepare a Linux box
2. Install RKE2
3. Install KubeVirt
4. Deploy KubeVirtBMC
5. Create a VirtualMachine with `.spec.running` field defined
6. Try to power on the VM using `ipmitool`

**Expected behavior**

Users should be able to power on and off the 

**Screenshots**

![image](https://github.com/user-attachments/assets/44fd00c1-97e5-4423-b286-07345992c06d)

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- Kubernetes version: v1.28.11+rke2r1
- KubeVirt version: v1.1.0
- KubeVirtBMC version: v0.3.0

**Additional context**

We only handle power on and off commands with VM [RunStrategy](https://kubevirt.io/user-guide/compute/run_strategies/). We better also have `.spec.running` taken into account.
