### ISSUE TITLE
[BUG] ImagePullBackOff for the KubeVirtBMC manager pod

### ISSUE THREAD

**Issue by starbops** [starbops/kubevirtbmc#85]
**Describe the bug**

After helm install the cert-manager chart and the KubeVirtBMC chart, the kubevirtbmc manager pod cannot run correctly. The events indicate that one of the container image cannot be pull down, which is for the `kube-rbac-proxy` container.

P.S. Please ignore the `429 Too Many Requests` for the primary container image pull error. It's an environment issue.

```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       18s                default-scheduler  Successfully assigned kubevirtbmc-system/kubevirtbmc-749966fc5-2mj4f to alfa-1-tink-system
  Warning  FailedMount     18s (x2 over 19s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "kubevirtbmc-webhook-server-cert" not fou
nd
  Normal   AddedInterface  17s                multus             Add eth0 [10.52.1.28/32] from k8s-pod-network
  Normal   Pulling         17s                kubelet            Pulling image "starbops/virtbmc-controller:v0.5.3"
  Warning  Failed          15s                kubelet            Failed to pull image "starbops/virtbmc-controller:v0.5.3": failed to pull and unpack image "d
ocker.io/starbops/virtbmc-controller:v0.5.3": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/starbops/vir
tbmc-controller/manifests/sha256:69400e246de0183f0d050a2841203491b2de1f6e0e50561d85f5e2bf476e4f47: 429 Too Many Requests - Server message: toomanyrequests: Yo
u have reached your unauthenticated pull rate limit. https://www.docker.com/increase-rate-limit
  Warning  Failed          15s                kubelet            Error: ErrImagePull
  Normal   Pulling         15s                kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0"
  Normal   Pulled          12s                kubelet            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0" in 3.345s (3.345s incl
uding waiting). Image size: 25163193 bytes.
  Normal   Created         12s                kubelet            Created container: kube-rbac-proxy
  Normal   Started         11s                kubelet            Started container kube-rbac-proxy
  Normal   BackOff         9s (x2 over 10s)   kubelet            Back-off pulling image "starbops/virtbmc-controller:v0.5.3"
  Warning  Failed          9s (x2 over 10s)   kubelet            Error: ImagePullBackOff
```

The spec of the container:

```yaml
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
```

The container image `gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0` is  inaccessible because of the [GCR retirement](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr).

**To Reproduce**

1. Install cert-manager
   ```shell
   helm upgrade --install cert-manager cert-manager \
     --repo=https://charts.jetstack.io \
     --namespace=cert-manager \
     --create-namespace \
     --version=v1.17.1 \
     --set=crds.enabled=true
   ```
2. Install KubeVirtBMC
   ```shell
   helm upgrade --install kubevirtbmc kubevirtbmc/kubevirtbmc \
     --namespace=kubevirtbmc-system \
     --create-namespace
   ```
3. Inspect the manager pod
   ```shell
   $ kubectl -n kubevirtbmc-system get pods -l kubernetes.io/name=kubevirtbmc -l app.kubernetes.io/component=manager
   NAME                          READY   STATUS             RESTARTS   AGE
   kubevirtbmc-749966fc5-2mj4f   1/2     ImagePullBackOff   0          9m11s
   ```

**Expected behavior**

The manager pod should be running fine after installation.

**Screenshots**

N/A

**Environment (please complete the following information):**

- OS: [e.g. SLES 15 SP5] SLE Micro 15 SP5
- Kubernetes distribution/version: [e.g. RKE2 v1.31.7+rke2r1] RKE2 v1.32.4+rke2r1
- Chart version: [e.g. 0.2.3] 0.2.3
- App version: [e.g. v0.5.3] v0.5.3

**Additional context**

This was announced way back in May 2024: kubernetes-sigs/kubebuilder#3907. We should decide which plan to adopt and take further actions to fix the issue ASAP.
